### ISSUE TITLE
Update `tokio-rustls` and `webpki-roots` dependencies

### ISSUE THREAD

**Issue by rneswold** [pimeys/hyper-alpn#17]
GitHub is now sending us security issues because we're indirectly pulling in this crate which is specifying v0.22 of `webpki-roots` and v0.23 of `tokio-rustls`.

Updating `webpki-roots` results in a deprecation warning but, otherwise, compiles. There appears to be a slight API change in `tokio-rustls`, so that will take more analysis to fix.

If these updates can be made, it shouldn't change the overall API, so it would only be a patch-level version change. That way we don't have to create issues up the chain.

**Comment by rex-remind101** [comment]
addressed here https://github.com/WalletConnect/hyper-alpn/pull/16

**Comment by rneswold** [comment]
Thank you!
