### ISSUE TITLE
"invalid socket address" when resolving host

### ISSUE THREAD

**Issue by 0x6273** [pimeys/hyper-alpn#5]
When making a GET request I get the following panic:
```
thread 'tests::get_file' panicked at 'called `Result::unwrap()` on an `Err` value:
Request(Error(Connect, Custom { kind: InvalidInput, error: "Couldn\'t resolve host: Custom { kind: InvalidInput, error: \"invalid socket address\" }" }))', src/libcore/result.rs:1165:5
```

Seems like it's caused by [line 133 in lib.rs](https://github.com/pimeys/hyper-alpn/blame/8acab4db71a3295c0ea0022e36cc05db0281a715/src/lib.rs#L133), where it looks like it's trying to convert the host string with `.to_socket_addrs()`, which seems to want both the host and the port number. I got it to work by with the following change:

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 961059a..f682966 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -130,7 +130,7 @@ impl AlpnConnector {
     }

     async fn resolve(dst: Destination) -> std::io::Result<net::SocketAddr> {
-        let addrs = dst.host().to_socket_addrs().await.map_err(|e| {
+        let addrs = (dst.host(), 0).to_socket_addrs().await.map_err(|e| {
             io::Error::new(
                 io::ErrorKind::InvalidInput,
                 format!("Couldn't resolve host: {:?}", e)
```

**Comment by pimeys** [comment]
Dear lord... Nice catch. Not an excuse, but not owning apple devices anymore and this one was for apns notifications. Of course you could write a test to the resolver, which I did, so here:

https://github.com/pimeys/hyper-alpn/commit/99c87c6c35e9c3cd2403b43670b8626e9cc251e9
